#!/usr/bin/env bash
# Copyright 2026 meatcar (@meatcar)
# SPDX-License-Identifier: GPL-2.0-or-later
set -euo pipefail

root=$(realpath "$(dirname "$0")/..")
keymap="$root/keyboards/ploopyco/madromys/keymaps/meatcar"
qmk="$root/qmk_firmware"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

for header in action keyboard timer wait keymap_common action_layer action_tapping action_util keymap_introspection caps_word quantum quantum_keycodes; do
    ln -s "$keymap/tests/qmk_stub.h" "$tmp/$header.h"
done
cp "$qmk/quantum/via.h" "$tmp/via.h"

flags=(-std=c11 -Wall -Wextra -Werror -Wno-unused-parameter -g -fsanitize=address,undefined
    -DCOMBO_ENABLE -DNO_ACTION_TAPPING '-DQMK_KEYBOARD_H="qmk_stub.h"'
    -include "$keymap/tests/qmk_stub.h"
    -I"$keymap/tests" -I"$keymap" -I"$tmp" -I"$qmk/quantum" -I"$qmk/quantum/process_keycode"
    -I"$qmk/quantum/keymap_extras" -I"$qmk/keyboards/ploopyco")
"${CC:-cc}" "${flags[@]}" "$keymap/keymap.c" "$keymap/tests/host.c" "$keymap/tests/test_adept.c" \
    "$qmk/quantum/process_keycode/process_combo.c" -o "$tmp/test-adept"
"$tmp/test-adept"
